### ISSUE TITLE
[bug] rocks-config + rocks-git breaks initialization

### ISSUE THREAD

**Issue by Quitlox** [nvim-neorocks/rocks-config.nvim#63] opened 2024-07-27 08:22 UTC
Hi there, thanks for this amazing project!

I am having trouble with the following configuration for installing `mistweaverco/kulala.nvim` (combining `rocks-git` with `rocks-config`). When I use the configuration below, syncing breaks. The only way to "fix" it is to manually reinstall the plugin after a broken sync. I have had this on two different machines.

It seems to me that the configuration of `kulala.nvim` is sourced even though `rocks-git` has yet to properly install the plugin.

#### `rocks.toml`
```toml
[rocks]
[plugins]
"rocks.nvim" = "2.36.1"
"rocks-git.nvim" = "2.0.1"
"rocks-config.nvim" = "2.1.4"

"kulala.nvim" = { git = "mistweaverco/kulala.nvim", rev = "v2.6.0", config = "plugins.http" }

[config]
plugins_dir = "plugins/"
auto_setup = false
```

Make sure to include the custom `config` parameter. Without, it seems to work just fine.

#### `plugins/http.lua`

```lua
require("kulala").setup()
```

#### `init.lua`

```lua
-- Up-to-date bootstrap script from README (placed in ./lua/bootstrap.lua)
require("bootstrap")
```

### Steps to Reproduce
1. `rm -rf ~/.local/share/nvim_rocks ~/.cache/nvim_rocks ~/.local/state/nvim_rocks`
2. `NVIM_APPNAME=nvim_rocks nvim` (config in `~/.config/nvim_rocks`)
3. `Rocks sync`

At this point, `Rocks log` outputs the following:
```
[START][2024-07-27 10:10:12] rocks.nvim logging initiated
ERROR | 2024-07-27 10:10:22 | ...nvim_rocks/rocks/rocks_rtp/lua/rocks/operations/sync.lua:48 | SYNC ERROR: Failed to install kulala.nvim: No version specified
ERROR | 2024-07-27 10:10:23 | ...nvim_rocks/rocks/rocks_rtp/lua/rocks/operations/sync.lua:267 | Sync completed with errors! Run ':Rocks log' for details.
```

4. Restart Neovim
```
Error detected while processing /home/quitlox/.local/share/nvim_rocks/rocks/lib/luarocks/rocks-5.1/rocks.nvim/2.36.1-1/plugin/rocks.lua:                   
E5113: Error while calling lua chunk: /home/quitlox/.config/nvim_rocks/lua/plugins/http.lua:1: module 'kulala' not found:No LuaRocks module found for kulal
a                                                                                                                                                          
        no field package.preload['kulala']                                                                                                                 
        no file './kulala.lua'                                                                                                                             
        no file '/usr/share/luajit-2.1/kulala.lua'                                                                                                         
        no file '/usr/local/share/lua/5.1/kulala.lua'                                                                                                      
        no file '/usr/local/share/lua/5.1/kulala/init.lua'                                                                                                 
        no file '/usr/share/lua/5.1/kulala.lua'                                                                                                            
        no file '/usr/share/lua/5.1/kulala/init.lua'                                                                                                       
        no file '/home/quitlox/.local/share/nvim_rocks/rocks/share/lua/5.1/kulala.lua'                                                                     
        no file '/home/quitlox/.local/share/nvim_rocks/rocks/share/lua/5.1/kulala/init.lua'                                                                
        no file '/home/quitlox/.local/share/nvim_rocks/rocks/share/lua/5.1/init.lua'                                                                       
        no file './kulala.so'                                                                                                                              
        no file '/usr/local/lib/lua/5.1/kulala.so'                                                                                                         
        no file '/usr/lib/lua/5.1/kulala.so'                                                                                                               
        no file '/usr/local/lib/lua/5.1/loadall.so'                                                                                                        
        no file '/home/quitlox/.local/share/nvim_rocks/rocks/lib/lua/5.1/kulala.so'                                                                        
        no file '/home/quitlox/.local/share/nvim_rocks/rocks/lib64/lua/5.1/kulala.so'                                                                      
stack traceback:                                                                                                                                           
        [C]: in function 'require'                                                                                                                         
        /home/quitlox/.config/nvim_rocks/lua/plugins/http.lua:1: in main chunk                                                                             
        [C]: in function 'require'                                                                                                                         
        ...nvim_rocks/rocks/rocks_rtp/lua/rocks-config/internal.lua:194: in function 'configure'                                                           
        ...nvim_rocks/rocks/rocks_rtp/lua/rocks-config/internal.lua:299: in function 'setup'                                                               
        ...rocks/rocks_rtp/lua/rocks-config/rocks/hooks/preload.lua:18: in function 'action'                                                               
        ...share/nvim_rocks/rocks/rocks_rtp/lua/rocks/api/hooks.lua:94: in function 'run_preload_hooks'                                                    
        .../luarocks/rocks-5.1/rocks.nvim/2.36.1-1/plugin/rocks.lua:61: in main chunk
```

To fix, I need to:
5. `Rocks install rocks-git.nvim`
6. `Rocks install mistweaverco/kulala.nvim`

P.S. I am not completely sure which rocks repository this issue belongs to.

Edit: I now notice that running `Rocks sync` twice on first initialization, gives `rocks-git` the chance to install the plugin, preventing the issue. Unfortunately, if you don't (know to) do this and restart after the first sync, the configuration breaks.

**Comment by mrcjkb** [comment] 2024-07-27 09:18
Hey :wave: 

thanks for the detailed report. I think I am able to reproduce the same (or similar) behaviour.
In my case, it appears to be because an error thrown by rocks-config.nvim when it can't find the `kulala` module prevents rocks-git.nvim from being registered as an extension.

**Comment by mrcjkb** [comment] 2024-07-27 09:24
Moving to rocks-config.nvim, as this is a rocks-config bug.

**Closed as completed** 2024-07-27 09:48 UTC

**Comment by mrcjkb** [comment] 2024-07-27 09:51
Just released rocks-config.nvim 2.1.5 with a fix.
